### ISSUE TITLE
can't find the paper that you mentioned 

### ISSUE THREAD

**Issue by lligen** [manhofer/Line3D#1]
hi,
i can't find the paper that you mentioned, can you upload it to git repo?

**Comment by manhofer** [comment]
Hi

The paper will be presented at this years GCPR in October and is currently
prepared for publication by Springer.

I can not upload it yet, but I hope soon. Please check our groups website
http://aerial.icg.tugraz.at I will put it there as soon as possible

Best,
Manuel
Am 06.09.2015 15:00 schrieb "lligen" notifications@github.com:

**Comment by lligen** [comment]
Well, thanks for your reply.
By the way, is there any introduction or resource with respect to the **Line3d** project? Or,  can this program afford real-time processing for robot pose localization? Any video available?

**Comment by manhofer** [comment]
Am 06.09.2015 um 15:48 schrieb lligen:

> Well, thanks for your reply.
> By the way, is there any introduction or resource with respect to the 
> _Line3d_ project? Or, can this program afford real-time processing for 
> robot pose localization? Any video available?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/manhofer/Line3D/issues/1#issuecomment-138086606.

Hi

The algorithm was developed in the course of my PhD program and within 
the founded projects PEGASUS and FreeLine, which focus on Power Pylon 
and Power Line inspection using UAVs. More infos here: 
https://aerial.icg.tugraz.at/funding.html

The whole thing (Line3D) is basically a multi-view stereo algorithm, 
similar to Furukawas PMVS but with lines. This means it needs the camera 
poses. So you need to perform Structure-from-motion first and then run 
Line3D as a post-processing. We have not yet tried to do a lot of 
real-time stuff, because pose estimation with lines is not so easy. 
Also, line matching without pose information is a bit of a pain in the 
ass. However, we have included similar methods to Line3D into an online 
SfM framework. That is not real-time but you can process an image per 
second or so. But the source-code for that is not (yet) available.

When you want to do pose localization with lines you should have a look 
at this paper: 
http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Micusik_Descriptor_Free_Visual_2015_CVPR_paper.pdf

A video for our previous method (which is quite similar to Line3D but 
not open-source) is available here: 
https://aerial.icg.tugraz.at/videos/3DV2014_Hofer_(1080p).mp4

Best,
Manuel

## 

Dipl.-Ing. Manuel Hofer
Schanzelgasse 24/23
A-8010 Graz

**Comment by lligen** [comment]
Thank you for your kind messages. I'm so grateful.

**Comment by lligen** [comment]
Thank you for your kind introduction. I'm so grateful.
